export const Resources = [
  ['background', 'res/bg_img@3x.png'],
  ['nav-back', 'res/back_ic@3x.png'],
  ['facaiwenda', 'res/facaiwenda_img@3x.png'],
  ['guize-bg-img', 'res/guize_bg_img@3x.png'],
  ['money', 'res/money_img@3x.png'],
  ['start-btn', 'res/guize_button@3x.png'],
  ['window-img', 'res/end_window_img@3x.png'],
  ['end-btn', 'res/button_again@3x.png'],
  ['coins-bg-img', 'res/coins_bg_img@3x.png'],
  ['answer-bgl-img', 'res/answer_bgl_img@3x.png'],
  ['button-default', 'res/button_default@3x.png'],
  ['button-wrong', 'res/button_wrong@3x.png'],
  ['button-right', 'res/button_right@3x.png'],
  ['TIPS_ic', 'res/TIPS_ic@3x.png'],
  ['add10s_ic', 'res/add10s_ic@3x.png'],
  ['AB_ic', 'res/AB_ic@3x.png'],
  ['title_ic', 'res/title_ic@3x.png'],
  ['button_close_ic', 'res/button_close_ic@3x.png'],
  ['window_img', 'res/window_img@3x.png'],
  ['button_check', 'res/button_check@3x.png'],
]